{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prettycode
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/prettycode_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prettycode/prettycode_{{ version }}.tar.gz
  sha256: 4f877bef2d4ff7771a3fa0368c9b85ef058b4c06ff9c18c31d827d3d0e4cd0c5

build:
  merge_build_host: True  # [win]
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crayon
    - r-withr
  run:
    - r-base
    - r-crayon
    - r-withr

test:
  commands:
    - $R -e "library('prettycode')"           # [not win]
    - "\"%R%\" -e \"library('prettycode')\""  # [win]

about:
  home: https://github.com/r-lib/prettycode#readme
  license: MIT
  license_file: 
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE
  summary: Replace the standard print method for functions with one that performs syntax highlighting,
    using ANSI colors, if the terminal supports them.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: prettycode
# Title: Pretty Print R Code in the Terminal
# Version: 1.0.2
# Author: Gabor Csardi
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Description: Replace the standard print method for functions with one that performs syntax highlighting, using ANSI colors, if the terminal supports them.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/r-lib/prettycode#readme
# BugReports: https://github.com/r-lib/prettycode/issues
# RoxygenNote: 6.1.0
# Imports: crayon, utils, withr
# Suggests: covr, mockery, testthat
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2018-09-11 10:53:52 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2018-09-11 11:10:02 UTC
