appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: HOA16qUUQnMHJ7YMdLXn3KqOIm3zvVYJimuEdRev0896VrT6IHZLn2ZkkJkOKCY6bBtt9aD/7QKyJHsAm+//jJy6Gi2YAEXONQ5eecThrj1otbOMUZurZc/6HNoxGPsNxiho4PW24q6SbOWFrNnWp/jJPynchbwT5afUTQAYcQCgU8wUyrmMgEaif2WCdZigbawFoIwipCKxMK6X7B1L3ina6MQORRo+zrB9i800RmXvxffzCgcjjjVViWFGglGBd1jyaXcwpz0FsJmqKJcO9hoxoJBFwx+UZX5vMp3yPt9/+IIN/VS+rz1B1NIRrAaUndEo/mfGtfXhq1wLxAG/Lj1Z4nsU2xs54T9R8Zh9VNJtcVmc+IboXiU8HTBIHhGyez/ibzPkR11ETJBRZS7FY0HWQEcEaXg2IFXZO9+6kO5b4unIuSFb3W9JNiXNGj5xJsWBgthmEZExEoOW27r+JY9ozPdSTU51eDZ84RY2IAqMMDeQjPoDrr+V3PFVvY1qOMoTC8AnBCV7ysk7+2CPBjvHTis4gR3ypNSVRxazQif51kzz2b9ZlwQcnwm+ATS8LaFRaiV0rj0QBKTHoFAOgZC32fZSu656cxQATOhFYeSpAqHxj1+bYE6o9nhCQFvBzSh56Wa4OOQJ6pZtI/q6Yq0j3VjghNfSedOiCrk1knM=}
bot:
  automerge: true
