travis:
  secure:
    BINSTAR_TOKEN: g5wrCPE2rXDDNsNqHnrHk/tlz4Jyl9o/IE6bNnfxIj65HLd8UaTB7m433QdsN5FD6oJ2dAVnkcgHBbHwyQ9547INtspcC+gAIxpF2GNl/fdCHsYO4I/XflTRghg+J1uL3FXy/Qyq+xNYfxlTL94o9G91I+NQTk8QBBitdxSGU0iUHoUMFjhkOyWTxobM1mdsHC/q8wBLj2WytTafyTVpJv3KMoMKODyXomIyIBjOm5qbu2ZHw04ekNoqYE4Yqsv6Shyi+cEVMhz+/xyzhdo3kGNdG6kH6z2Xksn41A9GWaBVCT29ZkFpPu1ULTBA6KXNgFJ/wezOKsMnf/AZxKbij0S1UB1kaP86TbSv2jDl5aEHn3LedRGrzsrULq7hhs17HBiZpgvaIles6p+l9Nsw3Lxy2usOQqtEseZM3CBVogBXNfpu+zmo2trCND7NDx3EoJNLbmLrPN4D8jWPKW0HgYTOvNjJT+nIJrGdV1JgDBRZbf0CSv0IXXMVAifdFp+omcQfq2hIyjX3r9D7CN+mvBpYnyVvRpSE6e8YoG0YNTunWIh93LgJiQjK3296HcoMUj1/16r+lVm8rWMyqEBHqarAxjpBIAxkJv3LSWNecuRtaUqxu0bvuwKudjWCVBj3Q89uYflNYhszOWY0/Xs0kMX09o60X1MxGYww2PRXYyo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
